apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aio-opc-ua-broker-trust-list
  namespace: azure-iot-operations
spec:
  provider: azure
  parameters:
    usePodIdentity: 'false'
    keyvaultName: "${aio_kv_name}"
    tenantId: ${aio_tenant_id}
    objects: |
      array:
        - |
          objectName: placeholder-secret
          objectType: secret
          objectVersion: ""
