apiVersion: mq.iotoperations.azure.com/v1beta1
kind: KafkaConnectorTopicMap
metadata:
  name: ${aio_eh_kafka_connector_topic_map_name}
  namespace: ${aio_cluster_namespace} # same as one used for other MQ resources
spec:
  kafkaConnectorRef: ${aio_eh_kafka_connector_name}
  # compression: snappy
  # batching:
  #   enabled: true
  #   latencyMs: 1000
  #   maxMessages: 100
  #   maxBytes: 1024
  # partitionStrategy: property
  # partitionKeyProperty: device-id
  # copyMqttProperties: true
  routes:
    # Subscribe from MQTT topic "temperature-alerts/#" and send to Kafka topic "receiving-event-hub"
    - mqttToKafka:
        name: "route1"
        mqttTopic: ${aio_eh_edge_to_cloud_mqtt_topic} #azure-iot-operations/data/opc.tcp/opc.tcp-1/#
        kafkaTopic: ${aio_eh_edge_to_cloud_kafka_topic}
        kafkaAcks: one
        qos: 1
        # sharedSubscription:
        #   groupName: group1
        #   groupMinimumShareNumber: 3
    # Pull from kafka topic "sending-event-hub" and publish to MQTT topic "heater-commands"
    - kafkaToMqtt:
        name: "route2"
        kafkaTopic: ${aio_eh_cloud_to_edge_kafka_topic}
        mqttTopic: ${aio_eh_cloud_to_edge_mqtt_topic}
        qos: 0