apiVersion: v1
kind: ConfigMap
metadata:
  name: opcplc-khi-config
  namespace: azure-iot-operations
data:
  opcplc-khi-config.json: |
    {
      "Folder": "KHI",
      "FolderList": [
        {
          "Folder": "PLC1",
          "NodeList": [
            {
              "NodeId": "KHI.PLC1.TN6",
              "Name": "PLC1_TN6",
              "DataType": "Int32",
              "Parameters": {
                "$type": "OpcPlc.PluginNodes.CountUpSimulatedParameters, opcplc",
                "IntervalMilliseconds": 500,
                "Start": 1,
                "StepBy": 5,
                "ShouldRestart": true,
                "RestartWhenGreaterThan": 500
              }
            },
            {
              "NodeId": "KHI.PLC0.ScenarioSliderStop",
              "Name": "PLC0_ScenarioSliderStop",
              "DataType": "String",
              "Parameters": {
                "$type": "OpcPlc.PluginNodes.SequenceSimulatedParameters, opcplc",
                "IntervalMilliseconds": 2000,
                "Values": ["TRUE", "FALSE"]
              }
            }
          ]
        }
      ],
      "NodeList": [
        {
          "NodeId": 3000,
          "Name": "TestAwgActualSpeed",
          "Description": "Rotational speed"
        },
        {
          "NodeId": "TestAwgaRMS"
        },
        {
          "NodeId": "3001",
          "Name": "TestAwgDKW",
          "DataType": "Float",
          "ValueRank": -1,
          "AccessLevel": "CurrentReadOrWrite",
          "Description": "Test AWG Value"
        }
      ]
    }