mqttBroker:
  authenticationMethod: serviceAccountToken
  serviceAccountTokenAudience: '${aio_mq_auth_sat_audience}'
  address: '${aio_mq_local_url}'
  caCertConfigMapRef: '${aio_trust_config_map_name}'
  caCertKey: '${aio_ca_cm_cert_name}'
  connectUserProperties:
    metriccategory: aio-opc
opcPlcSimulation:
  deploy: ${should_simulate_plc}
openTelemetry:
  enabled: true
  endpoints:
    default:
      uri: '${aio_otel_collector_address}'
      protocol: grpc
      emitLogs: false
      emitMetrics: true
      emitTraces: false
    geneva:
      uri: '${aio_geneva_collector_address}'
      protocol: grpc
      emitLogs: false
      emitMetrics: true
      emitTraces: false
      temporalityPreference: delta
secrets:
  kind: 'csi'
  csiServicePrincipalSecretRef: '${aio_csi_secret_name}'
  csiDriver: secrets-store.csi.k8s.io
