apiVersion: v1
kind: Service
metadata:
  name: opcplc-sim-new
  namespace: azure-iot-operations
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: opcplc-sim-new
  ports:
    - port: 50000
      protocol: TCP
      targetPort: 50000