apiVersion: apps/v1
kind: Deployment
metadata:
  name: opcplc-sim-new
  namespace: azure-iot-operations
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: opcplc-sim-new
  template:
    metadata:
      labels:
        app.kubernetes.io/name: opcplc
        app.kubernetes.io/instance: opcplc-sim-new
        app.kubernetes.io/version: 0.0.1
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: opcplc
          image: ghcr.io/agreaves-ms/iotedge/opc-plc:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 50000
          args:
            - "--ph=opcplc-sim-new.azure-iot-operations"
            - "--cdn=opcplc-sim-new.azure-iot-operations,opcplc-sim-new"
            - "--ut"
            - "--autoaccept"
            - "--sn=25"
            - "--sr=10"
            - "--fn=2000"
            - "--vfr=1000"
            - "--gn=5"
            - "--pn=50000"
            - "--maxsessioncount=100"
            - "--maxsubscriptioncount=100"
            - "--maxqueuedrequestcount=2000"
            - "--ses"
            - "--alm"
            - "--nfs=/app/opcplc-khi-config.json"
          volumeMounts:
            - name: opcplc-khi-config
              mountPath: /app/opcplc-khi-config.json
              subPath: opcplc-khi-config.json
            - name: opcplc-sim-new-pki
              mountPath: /app/pki/
          resources:
            limits:
              cpu: 500m
              memory: 768Mi
            requests:
              cpu: 125m
              memory: 192Mi
      volumes:
        - name: opcplc-khi-config
          configMap:
            name: opcplc-khi-config
        - name: opcplc-sim-new-pki
          emptyDir:
            sizeLimit: 64Mi