apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: aio-opc-asset-discovery
  labels:
    "app.kubernetes.io/part-of": aio
spec:
  selector:
    matchLabels:
      name: aio-opc-asset-discovery
  template:
    metadata:
      labels:
        name: aio-opc-asset-discovery
        "app.kubernetes.io/part-of": aio
    spec:
      containers:
      - name: aio-opc-asset-discovery
        image: 'mcr.microsoft.com/azureiotoperations/opcuabroker/discovery-handler:${aio_extension_version}.4'
        imagePullPolicy: Always
        resources:
          requests:
            memory: 64Mi
            cpu: 10m
          limits:
            memory: 300Mi
            cpu: 100m
        ports:
        - name: discovery
          containerPort: 80
        env:
        - name: DISCOVERY_HANDLERS_DIRECTORY
          value: /var/lib/akri
        - name: AKRI_AGENT_REGISTRATION
          value: 'true'
        volumeMounts:
        - name: discovery-handlers
          mountPath: /var/lib/akri
      volumes:
      - name: discovery-handlers
        hostPath:
          path: /var/lib/akri