apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aio-opc-ua-broker-trust-list
  namespace: ${aio_cluster_namespace}
spec:
  provider: azure
  parameters:
    usePodIdentity: 'false'
    keyvaultName: ${aio_keyvault_name}
    tenantId: ${aio_tenant_id}
    objects: |
      array:
        - |
          objectName: placeholder-secret
          objectType: secret
          objectVersion: ""